<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\DayBookController;
use App\Http\Controllers\FactoryController;
use App\Http\Controllers\JobController;
use App\Http\Controllers\LandController;
use App\Http\Controllers\LandTypeController;
use App\Http\Controllers\PartyCategoryController;
use App\Http\Controllers\PartyController;
use App\Http\Controllers\PartySubCategoryController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\PurchaseFileController;
use App\Http\Controllers\PurchaseItemController;
use App\Http\Controllers\SaleController;
use App\Http\Controllers\SaleLandCuttingController;
use App\Http\Controllers\ProjectSaleExemptionController;
use App\Http\Controllers\SaleProjectFileController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return auth()->check() ? redirect()->route('users.index') : redirect()->route('login');
});

Route::middleware('auth')->group(function () {
    Route::resource('users', UserController::class);
    Route::resource('customers', CustomerController::class)->except(['show']);
    Route::get('sale', [SaleController::class, 'index'])->name('sale.index');
    Route::get('sale/projects/{project}/exemption', [ProjectSaleExemptionController::class, 'edit'])->name('sale.projects.exemption.edit');
    Route::put('sale/projects/{project}/exemption', [ProjectSaleExemptionController::class, 'update'])->name('sale.projects.exemption.update');
    Route::get('sale/projects/{project}/files', [SaleProjectFileController::class, 'index'])->name('sale.files.index');
    Route::get('sale/projects/{project}/files/create', [SaleProjectFileController::class, 'create'])->name('sale.files.create');
    Route::post('sale/projects/{project}/files', [SaleProjectFileController::class, 'store'])->name('sale.files.store');
    Route::get('sale/files/{projectFile}/sale', [SaleProjectFileController::class, 'saleCreate'])->name('sale.files.sale.create');
    Route::put('sale/files/{projectFile}/area', [SaleProjectFileController::class, 'updateArea'])->name('sale.files.area.update');
    Route::post('sale/files/{projectFile}/sale', [SaleController::class, 'store'])->name('sale.files.sale.store');
    Route::get('sale/records/create', [SaleController::class, 'create'])->name('sale.records.create');
    Route::get('sale/records/{sale}/land-cuttings', [SaleLandCuttingController::class, 'index'])->name('sale.records.land-cuttings.index');
    Route::post('sale/records/{sale}/land-cuttings', [SaleLandCuttingController::class, 'store'])->name('sale.records.land-cuttings.store');
    Route::delete('sale/records/{sale}/land-cuttings/{land_cutting}', [SaleLandCuttingController::class, 'destroy'])->name('sale.records.land-cuttings.destroy');
    Route::get('purchase', [ProjectController::class, 'purchaseIndex'])->name('purchase.index');
    Route::get('purchase/files', [PurchaseFileController::class, 'index'])->name('purchase.files.index');
    Route::get('purchase/files/create', [PurchaseFileController::class, 'create'])->name('purchase.files.create');
    Route::post('purchase/files', [PurchaseFileController::class, 'store'])->name('purchase.files.store');
    Route::get('purchase/files/{purchase_file}/payment-sheet-pdf', [PurchaseFileController::class, 'paymentSheetPdf'])->name('purchase.files.payment-sheet-pdf');
    Route::get('purchase/files/{purchase_file}/documents', [PurchaseFileController::class, 'documents'])->name('purchase.files.documents');
    Route::get('purchase/files/{purchase_file}/sellers', [PurchaseFileController::class, 'sellers'])->name('purchase.files.sellers');
    Route::post('purchase/files/{purchase_file}/sellers', [PurchaseFileController::class, 'storeSellers'])->name('purchase.files.sellers.store');
    Route::delete('purchase/files/{purchase_file}/sellers/{purchase_item}', [PurchaseFileController::class, 'destroySeller'])->name('purchase.files.sellers.destroy');
    Route::post('purchase/files/{purchase_file}/sale-land', [PurchaseFileController::class, 'markSaleLand'])->name('purchase.files.sale-land');
    Route::get('purchase/files/{purchase_file}/edit', [PurchaseFileController::class, 'edit'])->name('purchase.files.edit');
    Route::put('purchase/files/{purchase_file}', [PurchaseFileController::class, 'update'])->name('purchase.files.update');
    Route::delete('purchase/files/{purchase_file}', [PurchaseFileController::class, 'destroy'])->name('purchase.files.destroy');
    Route::post('purchase/files/{purchase_file}/documents', [PurchaseFileController::class, 'storeDocuments'])->name('purchase.files.documents.store');
    Route::delete('purchase/files/{purchase_file}/documents/{document}', [PurchaseFileController::class, 'destroyDocument'])->name('purchase.files.documents.destroy');
    Route::get('purchase/lines/pdf', [PurchaseItemController::class, 'pdf'])->name('purchase.lines.pdf');
    Route::get('purchase/lines/ledger-pdf', [PurchaseItemController::class, 'ledgerPdf'])->name('purchase.lines.ledger-pdf');
    Route::get('purchase/records/create', [PurchaseItemController::class, 'create'])->name('purchase.records.create');
    Route::post('purchase/records/suggest-file-name', [PurchaseItemController::class, 'suggestFileName'])->name('purchase.records.suggest-file-name');
    Route::post('purchase/records', [PurchaseItemController::class, 'store'])->name('purchase.records.store');
    Route::get('purchase/records/{purchase_item}/edit', [PurchaseItemController::class, 'edit'])->name('purchase.records.edit');
    Route::put('purchase/records/{purchase_item}', [PurchaseItemController::class, 'update'])->name('purchase.records.update');
    Route::delete('purchase/records/{purchase_item}', [PurchaseItemController::class, 'destroy'])->name('purchase.records.destroy');
    Route::post('projects/quick-store', [ProjectController::class, 'quickStore'])->name('projects.quick-store');
    Route::post('parties/quick-store', [PartyController::class, 'quickStore'])->name('parties.quick-store');
    Route::post('party-sub-categories/quick-store', [PartySubCategoryController::class, 'quickStore'])->name('party-sub-categories.quick-store');
    Route::resource('parties', PartyController::class)->except(['show']);
    Route::get('projects/{project}/ledger-pdf', [ProjectController::class, 'ledgerPdf'])->name('projects.ledger.pdf');
    Route::get('projects/{project}/purchase', [ProjectController::class, 'purchase'])->name('projects.purchase');
    Route::get('projects/{project}/sale-land', [ProjectController::class, 'saleLand'])->name('projects.sale-land');
    Route::get('projects/{project}/sale-land-pdf', [ProjectController::class, 'saleLandPdf'])->name('projects.sale-land.pdf');
    Route::patch('projects/{project}/sale-land/moza-row', [ProjectController::class, 'updateSaleLandMozaRow'])->name('projects.sale-land.moza-row.update');
    Route::resource('projects', ProjectController::class);
    Route::post('projects/{project}/files', [ProjectController::class, 'addFile'])->name('projects.files.store');
    Route::put('projects/{project}/files/{projectFile}/sell', [ProjectController::class, 'sellFile'])->name('projects.files.sell');
    Route::post('projects/{project}/files/{projectFile}/documents', [ProjectController::class, 'uploadFileDocument'])->name('projects.files.documents.store');
    Route::delete('projects/{project}/files/{projectFile}/documents/{document}', [ProjectController::class, 'destroyFileDocument'])->name('projects.files.documents.destroy');
    Route::resource('lands', LandController::class);
    Route::post('lands/{land}/plots', [LandController::class, 'addPlot'])->name('lands.plots.store');
    Route::put('lands/{land}/plots/{plot}/sell', [LandController::class, 'sellPlot'])->name('lands.plots.sell');
    Route::post('lands/{land}/plots/{plot}/documents', [LandController::class, 'uploadPlotDocument'])->name('lands.plots.documents.store');
    Route::delete('lands/{land}/plots/{plot}/documents/{document}', [LandController::class, 'destroyPlotDocument'])->name('lands.plots.documents.destroy');
    Route::resource('factories', FactoryController::class);
    Route::get('daybook', [DayBookController::class, 'index'])->name('daybook.index');
    Route::get('daybook/entries', [DayBookController::class, 'entries'])->name('daybook.entries');
    Route::get('daybook/ledger', [DayBookController::class, 'ledger'])->name('daybook.ledger');
    Route::get('daybook/ledger/pdf', [DayBookController::class, 'ledgerPdf'])->name('daybook.ledger.pdf');
    Route::get('daybook/report/pdf', [DayBookController::class, 'reportPdf'])->name('daybook.report.pdf');
    Route::post('daybook/petty-cash', [DayBookController::class, 'updatePettyCash'])->name('daybook.petty-cash');
    Route::get('daybook/create', [DayBookController::class, 'create'])->name('daybook.create');
    Route::post('daybook', [DayBookController::class, 'store'])->name('daybook.store');
    Route::get('daybook/{entry}/voucher', [DayBookController::class, 'voucher'])->name('daybook.voucher');
    Route::get('daybook/{entry}', [DayBookController::class, 'show'])->name('daybook.show');
    Route::get('daybook/{entry}/edit', [DayBookController::class, 'edit'])->name('daybook.edit');
    Route::put('daybook/{entry}', [DayBookController::class, 'update'])->name('daybook.update');
    Route::delete('daybook/{entry}', [DayBookController::class, 'destroy'])->name('daybook.destroy');
    Route::resource('jobs', JobController::class);
    Route::resource('party-categories', PartyCategoryController::class)->except(['show']);
    Route::resource('party-sub-categories', PartySubCategoryController::class)->except(['show']);
    Route::resource('land-types', LandTypeController::class)->except(['show']);
    Route::get('settings', [SettingController::class, 'index'])->name('settings.index');
    Route::post('settings', [SettingController::class, 'update'])->name('settings.update');
    Route::post('/logout', [AuthController::class, 'logout'])->name('logout');
});

Route::get('/login', [AuthController::class, 'showLoginForm'])->name('login')->middleware('guest');
Route::post('/login', [AuthController::class, 'login'])->middleware('guest');
